### ISSUE TITLE
dREG Error

### ISSUE THREAD

**Issue by sahu0957** [Danko-Lab/dREG#10]
Running dREG through the web interface produces the following error:
Validation failed refer the validationResults list for detail error. Validation errors : Validation Errors : 

Inspecting the output files suggests that the bigWig files were made incorrectly, although both files are usable in other programs (genome viewers, for example). Output file states:
Every read might be mapped to a region, not a locus.

Further inspection of the files suggests that a solution could be found in the github repository Danko-Lab/dREGError, but I was unable to locate this repository, or any other info about why this error might come about.

Conversion to bigWig used RSeQC bam2wig.py and kentUtils wigToBigWig, as per the UCSC website. Additionally, I also attempted to create the bigWig files using bedtools to convert the sorted BAM files to BedGraph files, using bedtools slop and bedClip to ensure the regions did not extend past the ends of the chromosomes, and then used kentUtils bedGraphToBigWig, with the same result. See attached for scripts used and all output files.

[wigToBigWig.txt](https://github.com/Danko-Lab/dREG/files/2167905/wigToBigWig.txt)
[bedGraphToBigWig.txt](https://github.com/Danko-Lab/dREG/files/2167906/bedGraphToBigWig.txt)
[bam2wiggle.txt](https://github.com/Danko-Lab/dREG/files/2167907/bam2wiggle.txt)
[SRR1105736.out.dREG.log](https://github.com/Danko-Lab/dREG/files/2167885/SRR1105736.out.dREG.log)
[bg2bw.txt](https://github.com/Danko-Lab/dREG/files/2167948/bg2bw.txt)
[slurm-17717042.out.txt](https://github.com/Danko-Lab/dREG/files/2167949/slurm-17717042.out.txt)

**Comment by wzhy2000** [comment]
Sorry to check it just now. We do have a pipeline to make bigWig fiels:

https://github.com/Danko-Lab/proseq2.0
