### ISSUE TITLE
asvm.RData

### ISSUE THREAD

**Issue by azofeifa** [Danko-Lab/dREG#4]
Hi I am trying to run dREG on PRO-seq data. I understand I need the parameter file from the trained SVM. In the bash script, this is

asvm.RData

but can't seem to find/missed it somewhere in the github directories?

Thank you very much! Looking forward to getting this up and running! 
cheers!

**Comment by azofeifa** [comment]
ah! I found what look like dREG models at

https://github.com/Danko-Lab/dREG-Model

are these correct?
cheers

**Comment by dankoc** [comment]
Exactly right.  Keeping these large binary files in the same git repo runs the risk of causing problems in the long term.

Sorry for the confusion!
